### ISSUE TITLE
Error loading plugin within HDT

### ISSUE THREAD

**Issue by justadakaje** [CLJunge/Spawn.HDT.DustUtility#2]
I've downloaded latest release of both HDT and DustUtility. When attempting to enable DustUtility within HDT, I'm receiving the following error:

Make sure you are using the latest version of the Plugin and HDT.

System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Kenneth\AppData\Roaming\HearthstoneDeckTracker\DustUtility'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern)
   at Spawn.HDT.DustUtility.DustUtilityPlugin.UpdateHistoryFiles()
   at Spawn.HDT.DustUtility.DustUtilityPlugin.UpdateApp()
   at Spawn.HDT.DustUtility.DustUtilityPlugin.OnLoad()
   at Hearthstone_Deck_Tracker.Plugins.PluginWrapper.Load()

**Comment by CLJunge** [comment]
Have you used the plugin/HDT before or is this a clean installation?

One thing you can try is to run HDT as administrator and see if that works.
And please enable debug logging by setting the log level to 1.

**Comment by justadakaje** [comment]
I’ve been using HDT and other plugins for over a year, but this is first time using this one. I have experience with installing, running, and troubleshooting HDT plugins. The curious thing about this error is the path listed in the “Path Not Found”: “..\Appdata\Roaming\HearthstoneDeckTracker\DustUtility”. I don’t have DustUtility installed here. I extracted the .dll to the “\HDT\Plugins” Directory where my other plugins are located. Because I couldn’t find any install notes, I assumed to install this like any other HDT plugin. Is this correct?

**Comment by CLJunge** [comment]
I found the issue. The data directory hasn't been created when calling the UpdateApp function. And you are correct with installing it to the plugin directory.

I'll release an update with the fix asap. Thanks for your feedback!

**Comment by CLJunge** [comment]
I've released a new update. Could you please check if the issue still exists for you?

**Comment by justadakaje** [comment]
That resolved the issue! Thanks, CL
